[package]
name = "chapter20"
version = "0.1.0"
authors = ["Vadim Slynko <vadim@slynko.rocks>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
